project:
  type: website
  post-render:
    - "cp -rv static/. _site/"

website:
  title: "{{< var jpe.short >}} Data Editor"
  favicon: img/jpeicon.png
  page-footer: 
    left: "{{< var jpe.short >}} Data Editor: [{{< var de.mail >}}]({{< var de.mail >}}) <br> {{< var jpe.short >}} Journal Office: [{{< var jpe.mail >}}]({{< var jpe.mail >}})"
    center: "Â© [Florian Oswald](https://floswald.github.io) {{< var de.year >}}"
    right:
      - icon: github
        href: https://github.com/jpedataeditor

  # temporary
  announcement: 
    icon: cone-striped
    dismissable: false
    content: "This website is being built at the moment. Official Launch July 1st 2025."
    type: warning
    position: above-navbar

  sidebar:
    style: docked
    logo: img/jpe.jpg
    alignment: left
    contents: 
      - href: policy.qmd
        text: Code and Data Policy      
      - href: de.qmd
        text: Data Editor
      
  google-analytics:
    tracking-id: "G-48S9X9V28L"
    anonymize-ip: true
  cookie-consent: true

# format:
#   html:
#     theme: 
#       - cosmo
#       - mytheme.scss
#     toc: true
#     linkcolor: black



